### ISSUE TITLE
LogMiddleware should take an opaque datatype for the correlation ID

### ISSUE THREAD

**Issue by theophile-scrive** [scrive/wai-log#7]
Correlation (or Request) IDs are of varying formats, they can be UUIDs, but API gateways like Nginx do not always follow this (`$request_id` is a 32 haxadecimal characters string).

While the user can certainly use another field like `request_id` in their log metadata, it is far from ideal to have two competing ways to log a correlation ID. 

cc @arybczak @Siprj @wwwater

**Comment by Siprj** [comment]
I agree that the `request_id` should be treated as string and not as UUID. I am not sure how to tackle the API change, though.
